
version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: voting-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./backend
    container_name: voting-backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/voting
      - VITE_CONTROL_PASSWORD=meinPasswort
      - VITE_ALLOWED_HOSTS=localhost,example.com
      - VITE_VOTING_TITLE=Masked Singer Voting
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    container_name: voting-frontend
    environment:
      - VITE_VOTING_TITLE=Masked Singer Voting
    depends_on:
      - backend
  nginx:
    image: nginx:alpine
    container_name: voting-nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
volumes:
  mongo-data:
